#!/usr/bin/env bash

. ~/.config/cwm/lemonbar/bar_var

calendar() {
	date="$(date "+%a %d %b")"
	echo " ${DCOL} ${CLR}${date} "
}

clock() {
    time="$(date "+%H:%M")"
    echo " ${TCOL} ${CLR}${time} "
}
battery() {
    status="$(cat /sys/class/power_supply/AC/online)"
    battery="$(cat /sys/class/power_supply/BAT0/capacity)"
    timer="$(acpi -b | grep "Battery" | awk '{print $5}' | cut -c 1-5)"
    if [ "${status}" == 1 ]; then
      echo " ${BCOL} ${CLR}${battery}% "
    else
      echo " ${BCOL} ${CLR}${battery}% "
    fi
}
title() {
	title=`xtitle $(pfw)`
		[ -z "$title" ] && echo "" \
		|| echo " ${SEP} ${title} "
}
volume() {
	mix=`amixer get Master | tail -1`
	vol="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
	if [[ $mix == *\[off\]* ]]; then
	  echo " ${VCOL} ${CLR}Muted "
	else [[ $mix == *\[on\]* ]];
	  echo " ${VCOL} ${CLR}${vol}% "
	fi
}
wlan() {
	wifissid="$(nmcli -t -f NAME connection show --active)"
	wifiperc="$(grep "^\s*w" /proc/net/wireless | awk '{ print int($3 * 100 / 70) "%" }')"
    echo " ${WCOL} ${CLR}${wifiperc} ${wifissid} "
}
groups() {
ws=$( xprop -root _NET_CURRENT_DESKTOP | sed -e 's/_NET_CURRENT_DESKTOP(CARDINAL) = //' )
    for i in {1..5}; do
        # get the number of windows in each workspace
        windows=$( wmctrl -l | cut -d ' ' -f3 | grep $i | wc -l )

        if [[ $i -eq $ws ]]
        then
            # current workspace
            echo "${GCCOL}●${CLR}"
        elif [[ $windows -gt "0" ]]
        then
			# occupied workspace
			echo "${GPCOL}●${CLR}"
        else
            echo "${GECOL}●${CLR}"
        fi
    done
}

while :; do
 	buf=""
	buf="${buf}%{l}" #lemonbar align left
	buf="${buf} $(groups)"
	buf="${buf} $(title)"
#	buf="${buf}%{c}" #lemonbar align center
	buf="${buf}%{r}" # lemonbar align right
	buf="${buf}$(wlan)"
	buf="${buf} ${SEP}$(volume)"
	buf="${buf} ${SEP}$(battery)"
	buf="${buf} ${SEP}$(calendar)"
	buf="${buf} ${SEP}$(clock)"

	echo $buf
	sleep 0.5
done
