#!/bin/sh

DIALOG_RESULT=$(echo -e 'lock\nreboot\npoweroff\nexit' | dmenu -x "22" -y "27" -wi "125" -i -p "Power:" -l "4" )

echo "This result is : $DIALOG_RESULT"
sleep 1;

if [ "$DIALOG_RESULT" = "lock" ];
then
    exec ~/.bin/lock
elif [ "$DIALOG_RESULT" = "reboot" ];
then
    exec systemctl reboot
elif [ "$DIALOG_RESULT" = "poweroff" ];
then
    exec systemctl poweroff
elif [ "$DIALOG_RESULT" = "exit" ];
then
    exit 0
fi