#!/bin/sh

set -- $(dimensions)
w=$(echo "$1 / 3" | bc)
x=$(( $1 / 2 - $w / 2 ))
y=$(( $2 / 5 ))
h=$(( $2 / 50 ))
font="tewi:size=9:antialias=true:autohint=true"

dmenu_run -p "Run:" -i -f -fn "$font" -l "$h" -x "$x" -y "$y" -wi "$w"
