#! /bin/bash

FIFO=/tmp/bar.fifo

n="lemonbar-xft"
g="1366x20+0+0"
f1="tewi:size=9:antialias=true:autohint=true"
f2="siji:size=10:antialias=true:autohint=true"

BG="#1c1b1a"
FG="#f8f6f2"
BLACK="#141413"
BLACKER="#000000"
RED="#ff2c4b"
GREEN="#aeee00"
YELLOW="#fade3e"
BLUE="#0a9dff"
MAGENTA="#ff9eb8"
CYAN="#8cffba"
WHITE="#d9cec3"
SPEC="#45413b"

CLR="%{F$FG}%{B$BG}"
WSECOL="%{F$FG}%{B$BG}"
WSFCOL="%{F$GREEN}%{B$BLACKER}"
SEPCOL="%{F$SPEC}%{B$BG}"
TCOL="%{F$MAGENTA}%{B$BG}"
DCOL="%{F$RED}%{B$BG}"
VCOL="%{F$CYAN}%{B$BG}"
WCOL="%{F$BLUE}%{B$BG}"
BCOL="%{F$YELLOW}%{B$BG}"

SEP="${SEPCOL}|${CLR}"

print_workspaces() {
    while true; do
        cur=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
        tot=6
        seq=""

        for ((i=1;i<cur;i++)); do 
            seq+="${WSECOL} ${i} ${CLR}"
        done

        seq+="${WSFCOL} ${cur} ${CLR}"

        min=$cur+1
        for ((i=min;i<tot;i++)); do
            seq+="${WSECOL} ${i} ${CLR}"
        done

        echo "WORKSPACES ${seq}${CLR}"
        echo "WORKSPACES ${seq}"

        sleep 1
    done
}

print_battery() {
while true; do
  status="$(cat /sys/class/power_supply/AC/online)"
  battery="$(cat /sys/class/power_supply/BAT0/capacity)"
  timer="$(acpi -b | grep "Battery" | awk '{print $5}' | cut -c 1-5)"
  if [ "${status}" == 1 ]; then
    echo "BATTERY ${BCOL} ${CLR}${battery}%"
  else
    echo "BATTERY ${BCOL} ${CLR}${battery}%"
  fi
  sleep 1
done
}

print_wifi() {
while true; do
  wifissid="$(nmcli -t -f NAME connection show --active)"
  wifiperc="$(grep "^\s*w" /proc/net/wireless | awk '{ print int($3 * 100 / 70) "%" }')"
  echo "WIFI ${WCOL} ${CLR}${wifiperc} ${wifissid}"
  sleep 10
done
}

print_volume(){
while true; do
    mix=`amixer get Master | tail -1`
    vol="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
    if [[ $mix == *\[off\]* ]]; then
      echo "VOLUME ${VCOL} ${CLR}Muted"
    else [[ $mix == *\[on\]* ]];
      echo "VOLUME ${VCOL} ${CLR}${vol}%"
    fi
    sleep 1
done
}

print_date() {
while true; do
  date="$(date "+%a %d %b")"
  echo "DATE ${DCOL} ${CLR}${date}"
  sleep 5
done
}

print_time() {
while true; do
  time="$(date "+%H:%M")"
  echo "TIME ${TCOL} ${CLR}${time}"
  sleep 1
done
}

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT


[ -p "$FIFO" ] || mkfifo $FIFO

print_time			> $FIFO &
print_date			> $FIFO &
print_volume		> $FIFO &
print_wifi			> $FIFO &
print_battery		> $FIFO &
print_workspaces	> $FIFO &

while read -r line; do
    case $line in
        TIME*)
            fn_time="${line#TIME }";;
        DATE*)
            fn_date="${line#DATE }";;
        BATTERY*)
            fn_bat="${line#BATTERY }";;
        VOLUME*)
            fn_vol="${line#VOLUME }";;
        WIFI*)
            fn_wifi="${line#WIFI }";;
        WORKSPACES*)
            fn_ws="${line#WORKSPACES }";;
    esac
	printf "%s\n" " %{l}${fn_ws}%{r}${fn_wifi} ${SEP} ${fn_bat} ${SEP} ${fn_vol} ${SEP} ${fn_date} ${SEP} ${fn_time} "
done < $FIFO | lemonbar -d -p -n $n -g $g -f "$f1" -f "$f2" -B $BG -F $FG | sh &

wid=`xdo id -m -a $n`
xdo above -t `xdo id -N cwm -n root | sort | head -n 1` $wid

wait
